### ISSUE TITLE
How to load csv files to duckdb

### ISSUE THREAD

**Issue by ChampionNan** [Tmonster/verify_db_scripts#1]
Hi, 

Sorry to bother you. As for the original files at `http://homepages.cwi.nl/~boncz/job/imdb.tgz`, I found there are multiple errors when loading data to duckdb. How do you load the original data to it? 

Thanks!

**Comment by Tmonster** [comment]
Take a look at [load.sql](https://github.com/duckdb/duckdb/blob/main/benchmark/imdb/init/load.sql) in the duckdb repo. Those links should work
